### ISSUE TITLE
decouple find-tools requirements

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/devconsole-operator#58]
```
$ make lint
Searching for required executables: go gofmt dep git oc operator-sdk sed yamllint find grep...
```

If I wanted to checkout source code and run a `make lint` , why should I have `operator-sdk` ? :)

**Comment by tinakurian** [comment]
Lets use Jira to track all our work going forward. Created a bug here for this: https://jira.coreos.com/browse/ODC-415
