### ISSUE TITLE
e2e tests against openshift 4

### ISSUE THREAD

**Issue by sbose78** [redhat-developer/devconsole-operator#66]
In OpenShift 4, 
- olm would already be installed
- the namespaces `olm` and `operators` probably aren't present.

The `make test-olm-integration` target needs to be refactored to read an env var `OPENSHIFT_VERSION=4 make test-olm-integration` or `OPENSHIFT_VERSION=3 make make test-olm-integration` and accordingly create resources.

https://jira.coreos.com/browse/ODC-402

**Comment by tinakurian** [comment]
Lets use Jira to track this. Looks like there is already something there to track this work. Closing!
